# Generated by Django 3.1.3 on 2020-11-27 11:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201127_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='badges',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Работа с НЗОК', 'Работа с НЗОК'), ('Обявени цени', 'Обявени цени'), ('Приемане по спешност', 'Приемане по спешност'), ('Работа с деца', 'Работа с деца'), ('Хомеопатия', 'Хомеопатия')], max_length=72, null=True),
        ),
    ]
