# Generated by Django 3.1.3 on 2020-11-27 12:01

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), blank=True, size=None),
        ),
    ]
