# Generated by Django 3.1.3 on 2020-11-23 16:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201123_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='insurers',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Алианц', 'Алианц'), ('Булстрад Живот', 'Булстрад Живот'), ('България Иншурънс', 'България Иншурънс'), ('ДЗИ', 'ДЗИ'), ('ЕЗОК', 'ЕЗОК'), ('Дженерали', 'Дженерали'), ('Доверие', 'Доверие'), ('Евроинс', 'Евроинс'), ('Животозастрахователен Институт', 'Животозастрахователен институт'), ('Медико-21', 'Медико-21'), ('ОЗОК инс', 'ОЗОК инс'), ('Съгласие', 'Съгласие'), ('Уника', 'Уника'), ('FiHealth', 'FiHealth')], max_length=148),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.CharField(choices=[('Благоевград', 'Благоевград'), ('Бургас', 'Бургас'), ('Варна', 'Варна'), ('Велико Търново', 'Велико Търново'), ('Видин', 'Видин'), ('Враца', 'Враца'), ('Габрово', 'Габрово'), ('Добрич', 'Добрич'), ('Кърджали', 'Кърджали'), ('Кюстендил', 'Кюстендил'), ('Ловеч', 'Ловеч'), ('Монтана', 'Монтана'), ('Пазарджик', 'Пазарджик'), ('Перник', 'Перник'), ('Плевен', 'Плевен'), ('Пловдив', 'Пловдив'), ('Разград', 'Разград'), ('Русе', 'Русе'), ('Силистра', 'Силистра'), ('Сливен', 'Сливен'), ('Смолян', 'Смолян'), ('София', 'София'), ('Стара Загора', 'Стара Загора'), ('Търговище', 'Търговище'), ('Хасково', 'Хасково'), ('Шумен', 'Шумен'), ('Ямбол', 'Ямбол')], default='София', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
