# Generated by Django 3.1.3 on 2020-11-27 12:05

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201127_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateTimeField(), blank=True, size=None),
        ),
    ]
