# Generated by Django 3.1.3 on 2020-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201123_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='region',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
