# Generated by Django 3.1.3 on 2020-12-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201202_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='id',
            new_name='uid',
        ),
    ]
