# Generated by Django 3.1.3 on 2020-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201123_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Благоевград', 'Благоевград'), ('Бургас', 'Бургас'), ('Варна', 'Варна'), ('Велико Търново', 'Велико Търново'), ('Видин', 'Видин'), ('Враца', 'Враца'), ('Габрово', 'Габрово'), ('Добрич', 'Добрич'), ('Кърджали', 'Кърджали'), ('Кюстендил', 'Кюстендил'), ('Ловеч', 'Ловеч'), ('Монтана', 'Монтана'), ('Пазарджик', 'Пазарджик'), ('Перник', 'Перник'), ('Плевен', 'Плевен'), ('Пловдив', 'Пловдив'), ('Разград', 'Разград'), ('Русе', 'Русе'), ('Силистра', 'Силистра'), ('Сливен', 'Сливен'), ('Смолян', 'Смолян'), ('София', 'София'), ('Стара Загора', 'Стара Загора'), ('Търговище', 'Търговище'), ('Хасково', 'Хасково'), ('Шумен', 'Шумен'), ('Ямбол', 'Ямбол')], default='София', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='works_in',
            field=models.ManyToManyField(blank=True, to='api.Clinic'),
        ),
    ]
