# Generated by Django 3.1.3 on 2020-11-25 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201123_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='tes', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='sasda', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='account-images/%Y/%m/%d/')),
                ('multiImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
