# Generated by Django 3.1.3 on 2020-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_timeslot_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.JSONField(),
        ),
    ]
