# Generated by Django 3.1.3 on 2020-11-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201127_1143'),
        ('api', '0017_remove_timeslot_time_slot'),
    ]

    operations = [
    ]
